language: haskell
sudo: false
ghc: 7.8
after_success:
- find . -type f
- chmod 600 id_rsa.polysquare-builder
- mkdir -p ~/.ssh
- mv id_rsa.polysquare-builder.pub ~/.ssh/id_rsa.pub
- mv id_rsa.polysquare-builder ~/.ssh/id_rsa
- git clone git@github.com:polysquare-builds/polysquare-haskell-builds
- host_dir=$(curl -LSs "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD"
  | bash)
- mkdir -p "polysquare-haskell-builds/${host_dir}"
- cp "dist/build/pandoc/pandoc" "polysquare-haskell-builds/${host_dir}/pandoc"
- cd polysquare-haskell-builds
- git add "${host_dir}/pandoc"
- git config user.email "polysquare.builder@gmail.com"
- git config user.name "Polysquare Automated Builder"
- git commit -a -m "Automated update of pandoc'"
- git push origin master
before_install:
- openssl aes-256-cbc -K $encrypted_48e62671dfb2_key -iv $encrypted_48e62671dfb2_iv
  -in id_rsa.polysquare-builder.enc -out id_rsa.polysquare-builder -d
